[build]
	base = 'site/'
	publish = 'public/'
	
	HUGO_VERSION = '0.60.1'
	HUGO_ENV = 'development'
	HUGO_ENABLEGITINFO = 'true'
	command = 'hugo --gc'
	

[context.production]
	HUGO_ENV = 'production'
  command = 'hugo --gc --minify'
