[build]
	base = 'site/'
	publish = 'public/'
	command = 'hugo --gc'
	HUGO_VERSION = '0.60.1'
	HUGO_ENV = 'development'
	HUGO_ENABLEGITINFO = 'true'

[context.production]
  command = 'hugo --gc --minify'
	HUGO_ENV = 'production'
