[build]
	base = 'site/'
	publish = 'public/'
	command = 'hugo --gc'

[build.environment]
	HUGO_VERSION = '0.60.1'
	HUGO_ENV = 'development'
	HUGO_ENABLEGITINFO = 'true'

[context.production]
	command = 'hugo --gc --minify'
[context.production.environment]
	HUGO_ENV = 'production'
	HUGO_ENABLEGITINFO = 'false'
[context.production.processing]
	skip_processing = false
[context.production.processing.html]
	pretty_urls = true
[build.processing.images]
	compress = true

[[redirects]]
  from = '/*'
	to = '/404.html'
  status = 404
