baseURL = ''
uglyURLs = true

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
title = 'Hugo Page Template'

disableKinds = ['home', 'taxonomy', 'taxonomyTerm', 'RSS']

[params]
	production = false

[languages]
	[languages.en]
		languageName = 'English'
		languageCode = 'en'
		weight = 1
	[languages.de]
		title = 'Hugo Seitenvorlage'
		languageName = 'Deutsch'
		languageCode = 'de'
		weight = 2