baseURL = '/'
uglyURLs = false

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
title = 'Hugo Page Template'

disableKinds = ['taxonomy', 'taxonomyTerm', 'RSS']

[languages]
	[languages.en]
		languageName = 'English'
		languageCode = 'en'
		weight = 1
	[languages.de]
		title = 'Hugo Seitenvorlage'
		languageName = 'Deutsch'
		languageCode = 'de'
		weight = 2