baseURL = '/'
uglyURLs = false

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
title = 'Hugo Page Template'

disableKinds = ['taxonomy', 'taxonomyTerm', 'RSS']

[languages]
	[languages.en]
		weight = 1
		languageName = 'English'
		languageCode = 'en'
		#contentDir = 'content/en'
	[languages.de]
		weight = 2
		title = 'Hugo Seitenvorlage'
		languageName = 'Deutsch'
		languageCode = 'de'
		#contentDir = 'content/de'
