baseURL = ''
uglyURLs = true

defaultContentLanguage = 'en' # Placeholder to allow language files
defaultContentLanguageInSubdir = true
title = 'Hugo Page Template'

[params]
	production = false

[languages]
	[languages.en]
		languageName = 'English'
		languageCode = 'en'
		weight = 1
	[languages.de]
		title = 'Hugo Seitenvorlage'
		languageName = 'Deutsch'
		languageCode = 'de'
		weight = 2