baseURL = ''
defaulContentLanguage = 'en'
title = 'Hugo Page Template'

uglyURLs = true

[params]
	production = false

[languages]
	[languages.en]
		languageName = 'English'
		languageCode = 'en'
		contentDir = 'content/en'
		weight = 1
	[languages.de]
		languageName = 'Deutsch'
		languageCode = 'de'
		contentDir = 'content/de'
		weight = 2